import { colors } from "./colors";

export const snippetTheme = {
	additionColor: "#00ff00",
	attributeColor: "red",
	backgroundColor: colors.violet300,
	builtInColor: "#0077ff",
	bulletColor: "#ffaa00",
	codeColor: colors.blue,
	commentColor: "#777",
	deletionColor: "#ff0000",
	docTagColor: "#aa00ff",
	functionColor: colors.pink,
	keywordColor: colors.blue,
	lineNumberBgColor: "#222",
	lineNumberColor: "#ccc",
	linkColor: "#aa00ff",
	literalColor: "#ffaa00",
	metaColor: "#aa00ff",
	metaKeywordColor: "#f8f8f8",
	nameColor: "#f8f8f8",
	numberColor: colors.yellow,
	quoteColor: "#f8f8f8",
	regexpColor: "#f8f8f8",
	sectionColor: "#0077ff",
	selectorAttributeColor: "#ffaa00",
	selectorClassColor: "red",
	selectorIdColor: "#ffaa00",
	selectorPseudoColor: "#aa00ff",
	selectorTagColor: "red",
	stringColor: colors.green,
	substringColor: "red",
	symbolColor: "#ffaa00",
	templateTagColor: "red",
	templateVariableColor: "#ffaa00",
	textColor: "white",
	titleColor: "#0077ff",
	typeColor: "#0077ff",
	variableColor: "#ffaa00",
};
