description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v5
      with:
        cache: pnpm
        node-version: "22"
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite
