jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm build:dist

name: Build

on:
  pull_request: ~
  push:
    branches:
      - main
