jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm build:all
      - run: for file in ./packages/*/lib/index.js; do node $file; done

name: Build All

on:
  pull_request: ~
  push:
    branches:
      - main
