jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/prepare
      - run: pnpm run -r prebuild
      - run: pnpm run build
      - run: pnpm run build:all
      - run: pnpm lint

name: Lint

on:
  pull_request: ~
  push:
    branches:
      - main
